---
book_repo: pivotal-cf/docs-book-tiledev
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
  - repository:
    name: pivotal-cf/docs-tiledev
    ref: '2.6'
  directory: tiledev/2-6
  subnav_template: tiledev_subnav_2_6.erb
  product_info:
    use_local_header: true
    latest_stable_version: '2.5'
    changelog_href: http://docs.pivotal.io/tiledev/2-6/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Tile Developer Guide
    search_placeholder: Search PCF Tile Developer Guide 2.6
    local_product_version: '2.6'
    url_prefix: tiledev/2-6
    local_header_links:
      - <a href="https://network.pivotal.io/">Download</a>
      - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
      - <a href="https://discuss.pivotal.io/hc/en-us/categories/200072648-Pivotal-CF-Knowledge-Base">PCF Knowledge Base</a>
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/tiledev/2-5
        display_name: v2.5
      - url_prefix: https://docs.pivotal.io/tiledev/2-4
        display_name: v2.4
      - url_prefix: https://docs.pivotal.io/tiledev/2-3
        display_name: v2.3
      - url_prefix: https://docs.pivotal.io/tiledev/2-2
        display_name: v2.2
      - url_prefix: https://docs.pivotal.io/tiledev/2-1
        display_name: v2.1
      - <a href="https://docs.pivotal.io/archives/tiledev-guide-2.0.pdf">v2.0</a>
      - <a href="https://docs.pivotal.io/archives/tiledev-guide-1.12.pdf">v1.12</a>
  - repository:
      name: pivotal-cf/docs-tiledev
      ref: '2.5'
    directory: tiledev/2-5
    subnav_template: tiledev_subnav_2_5.erb
    product_info:
      use_local_header: true
      latest_stable_version: '2.5'
      changelog_href: http://docs.pivotal.io/tiledev/2-5/release-notes.html
      local_header_img: /images/cloud_rings.png
      local_header_title: PCF Tile Developer Guide
      search_placeholder: Search PCF Tile Developer Guide 2.5
      local_product_version: '2.5'
      url_prefix: tiledev/2-5
      local_header_links:
        - <a href="https://network.pivotal.io/">Download</a>
        - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
        - <a href="https://discuss.pivotal.io/hc/en-us/categories/200072648-Pivotal-CF-Knowledge-Base">PCF Knowledge Base</a>
      local_header_version_list:
        - url_prefix: https://docs.pivotal.io/tiledev/2-4
          display_name: v2.4
        - url_prefix: https://docs.pivotal.io/tiledev/2-3
          display_name: v2.3
        - url_prefix: https://docs.pivotal.io/tiledev/2-2
          display_name: v2.2
        - url_prefix: https://docs.pivotal.io/tiledev/2-1
          display_name: v2.1
        - <a href="https://docs.pivotal.io/archives/tiledev-guide-2.0.pdf">v2.0</a>
        - <a href="https://docs.pivotal.io/archives/tiledev-guide-1.12.pdf">v1.12</a>
  - repository:
      name: pivotal-cf/docs-tiledev
      ref: '2.4'
    directory: tiledev/2-4
    subnav_template: tiledev_subnav_2_4.erb
    product_info:
      use_local_header: true
      latest_stable_version: '2.5'
      changelog_href: http://docs.pivotal.io/tiledev/2-4/release-notes.html
      local_header_img: /images/cloud_rings.png
      local_header_title: PCF Tile Developer Guide
      search_placeholder: Search PCF Tile Developer Guide 2.4
      local_product_version: '2.4'
      url_prefix: tiledev/2-4
      local_header_links:
        - <a href="https://network.pivotal.io/">Download</a>
        - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
        - <a href="https://discuss.pivotal.io/hc/en-us/categories/200072648-Pivotal-CF-Knowledge-Base">PCF Knowledge Base</a>
      local_header_version_list:
        - url_prefix: https://docs.pivotal.io/tiledev/2-5
          display_name: v2.5
        - url_prefix: https://docs.pivotal.io/tiledev/2-3
          display_name: v2.3
        - url_prefix: https://docs.pivotal.io/tiledev/2-2
          display_name: v2.2
        - url_prefix: https://docs.pivotal.io/tiledev/2-1
          display_name: v2.1
        - <a href="https://docs.pivotal.io/archives/tiledev-guide-2.0.pdf">v2.0</a>
        - <a href="https://docs.pivotal.io/archives/tiledev-guide-1.12.pdf">v1.12</a>
  - repository:
      name: pivotal-cf/docs-tiledev
      ref: '2.3'
    directory: tiledev/2-3
    subnav_template: tiledev_subnav_2_3.erb
    product_info:
      use_local_header: true
      latest_stable_version: '2.5'
      changelog_href: http://docs.pivotal.io/tiledev/2-3/release-notes.html
      local_header_img: /images/cloud_rings.png
      local_header_title: PCF Tile Developer Guide
      search_placeholder: Search PCF Tile Developer Guide 2.3
      local_product_version: '2.3'
      url_prefix: tiledev/2-3
      local_header_links:
        - <a href="https://network.pivotal.io/">Download</a>
        - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
        - <a href="https://discuss.pivotal.io/hc/en-us/categories/200072648-Pivotal-CF-Knowledge-Base">PCF Knowledge Base</a>
      local_header_version_list:
        - url_prefix: https://docs.pivotal.io/tiledev/2-5
          display_name: v2.5
        - url_prefix: https://docs.pivotal.io/tiledev/2-4
          display_name: v2.4
        - url_prefix: https://docs.pivotal.io/tiledev/2-2
          display_name: v2.2
        - url_prefix: https://docs.pivotal.io/tiledev/2-1
          display_name: v2.1
        - <a href="https://docs.pivotal.io/archives/tiledev-guide-2.0.pdf">v2.0</a>
        - <a href="https://docs.pivotal.io/archives/tiledev-guide-1.12.pdf">v1.12</a>
  - repository:
      name: pivotal-cf/docs-tiledev
      ref: '2.2'
    directory: tiledev/2-2
    subnav_template: tiledev_subnav_2_2.erb
    product_info:
      use_local_header: true
      latest_stable_version: '2.5'
      changelog_href: http://docs.pivotal.io/tiledev/2-2/release-notes.html
      local_header_img: /images/cloud_rings.png
      local_header_title: PCF Tile Developer Guide
      search_placeholder: Search PCF Tile Developer Guide 2.2
      local_product_version: '2.2'
      url_prefix: tiledev/2-2
      local_header_links:
        - <a href="https://network.pivotal.io/">Download</a>
        - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
        - <a href="https://discuss.pivotal.io/hc/en-us/categories/200072648-Pivotal-CF-Knowledge-Base">PCF Knowledge Base</a>
      local_header_version_list:
        - url_prefix: https://docs.pivotal.io/tiledev/2-5
          display_name: v2.5
        - url_prefix: https://docs.pivotal.io/tiledev/2-4
          display_name: v2.4
        - url_prefix: https://docs.pivotal.io/tiledev/2-3
          display_name: v2.3
        - url_prefix: https://docs.pivotal.io/tiledev/2-1
          display_name: v2.1
        - <a href="https://docs.pivotal.io/archives/tiledev-guide-2.0.pdf">v2.0</a>
        - <a href="https://docs.pivotal.io/archives/tiledev-guide-1.12.pdf">v1.12</a>
  - repository:
      name: pivotal-cf/docs-tiledev
      ref: '2.1'
    directory: tiledev/2-1
    subnav_template: tiledev_subnav_2_1.erb
    product_info:
      use_local_header: true
      latest_stable_version: '2.5'
      changelog_href: http://docs.pivotal.io/tiledev/2-1/release-notes.html
      local_header_img: /images/cloud_rings.png
      local_header_title: PCF Tile Developer Guide
      search_placeholder: Search PCF Tile Developer Guide 2.1
      local_product_version: '2.1'
      url_prefix: tiledev/2-1
      local_header_links:
        - <a href="https://network.pivotal.io/">Download</a>
        - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
        - <a href="https://discuss.pivotal.io/hc/en-us/categories/200072648-Pivotal-CF-Knowledge-Base">PCF Knowledge Base</a>
      local_header_version_list:
        - url_prefix: https://docs.pivotal.io/tiledev/2-5
          display_name: v2.5
        - url_prefix: https://docs.pivotal.io/tiledev/2-4
          display_name: v2.4
        - url_prefix: https://docs.pivotal.io/tiledev/2-3
          display_name: v2.3
        - url_prefix: https://docs.pivotal.io/tiledev/2-2
          display_name: v2.2
        - <a href="https://docs.pivotal.io/archives/tiledev-guide-2.0.pdf">v2.0</a>
        - <a href="https://docs.pivotal.io/archives/tiledev-guide-1.12.pdf">v1.12</a>

template_variables:
  use_global_header: true
  book_title: Pivotal Documentation
  book_title_short: Pivotal Docs
  title: <span class="title-deemph">Pivotal</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with Pivotal's enterprise-grade software."
  product_full: Elastic Runtime
  product_short: Elastic Runtime
  product_name: PCF
  product_abbr:
  product_url: https://network.pivotal.io/products/pivotal-cf
  product_link: <div class="header-item"><a href="https://network.pivotal.io/products/pivotal-cf">Back to Product Page</a></div>
  service_name: PCF Tile Developer Guide
  service_name_article: PCF Tile Developer Guide
  service_name_article_full: PCF Tile Developer Guide
  support_link: <a href="http://support.pivotal.io" target="_blank">Support</a>
  support_call_to_action: <a href="http://support.pivotal.io" target="_blank">Need Support?</a>
  support_url: http://support.pivotal.io

  gtm_account_id: GTM-MW4LZHR
