---
book_repo: pivotal-cf/docs-book-tiledev
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'
book_title: PCF Tile Developers Guide

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

pcf_header: &local_pcf
  use_local_header: true
  latest_stable_version: '1.12'
  changelog_href: http://docs.pivotal.io/pivotalcf/pcf-release-notes/
  local_header_img: /images/cloud_rings.png
  local_header_title: Pivotal Cloud Foundry
  search_placeholder: Search Tile Developers Guide
  local_product_version: '1.12'
  url_prefix: tiledev

sections:
  - repository:
      name: pivotal-cf/docs-tiledev
    directory: tiledev
    subnav_template: tiledev_subnav.erb 

template_variables:                             # optional
