---
book_repo: pivotal-cf/docs-book-tiledev
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'edge'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
  - repository:
      name: pivotal-cf/docs-tiledev
      ref: 'master'
    directory: tiledev/2-n
    subnav_template: tiledev_subnav_2_n.erb 
    product_info:
      use_local_header: true
      latest_stable_version: '2.7'
      changelog_href: http://docs.pivotal.io/tiledev/2-n/release-notes.html
      local_header_img: /images/cloud_rings.png
      local_header_title: Pivotal Platform Tile Developer Guide
      search_placeholder: Search Pivotal Platform Tile Developer Guide 2.n
      local_product_version: '2.8'
      url_prefix: tiledev/2-n
      local_header_links:
        - <a href="https://network.pivotal.io/">Download</a>
        - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
        - <a href="https://community.pivotal.io/s/topic/0TO0P000000IKhwWAG/welcome">Pivotal Support Community</a>
      local_header_version_list:
        - url_prefix: https://docs.pivotal.io/tiledev/2-7
          display_name: v2.7
        - url_prefix: https://docs.pivotal.io/tiledev/2-6
          display_name: v2.6
        - url_prefix: https://docs.pivotal.io/tiledev/2-5
          display_name: v2.5
        - url_prefix: https://docs.pivotal.io/tiledev/2-4
          display_name: v2.4
        - url_prefix: https://docs.pivotal.io/tiledev/2-3
          display_name: v2.3
        - url_prefix: https://docs.pivotal.io/tiledev/2-2
          display_name: v2.2
        - url_prefix: https://docs.pivotal.io/tiledev/2-1
          display_name: v2.1
        - url_prefix: https://docs.pivotal.io/tiledev/2-0
          display_name: v2.0
        - url_prefix: https://docs.pivotal.io/tiledev/1-12
          display_name: v1.12

template_variables:
  use_global_header: true
  book_title: Pivotal Documentation
  book_title_short: Pivotal Docs
  title: <span class="title-deemph">Pivotal</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with Pivotal's enterprise-grade software."

  product_full: Pivotal Application Service (PAS)
  product_short: PAS
  product_windows: PASW
  product_windows_full: Pivotal Application Service for Windows (PASW)
  product_name: Pivotal Platform
  product_name_lc: pcf
  product_name_code_embed: PCF
  product_runtime: Pivotal Application Service
  product_abbr: 
  product_dev_local: Pivotal Dev
  product_url: https://network.pivotal.io/products/pivotal-cf
  product_link: <div class="header-item"><a href="https://network.pivotal.io/products/pivotal-cf">Back to Product Page</a></div>
  service_name: Pivotal Platform Tile Developer Guide
  service_name_article: Pivotal Platform Tile Developer Guide
  service_name_article_full: Pivotal Platform Tile Developer Guide
  support_link: <a href="http://support.pivotal.io" target="_blank">Support</a>
  support_call_to_action: <a href="http://support.pivotal.io" target="_blank">Need Support?</a>
  support_url: http://support.pivotal.io

  gtm_account_id: GTM-MW4LZHR
  
