---
book_repo: pivotal-cf/docs-book-tiledev
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
  - repository:
      name: pivotal-cf/docs-tiledev
      ref: '1.12'
    directory: tiledev/1-12
    subnav_template: tiledev_subnav.erb 
    product_info:
      use_local_header: true
      latest_stable_version: '1.12'
      changelog_href: http://docs.pivotal.io/tiledev/1-12/release-notes-1-12.html
      local_header_img: /images/cloud_rings.png
      local_header_title: Pivotal Cloud Foundry
      search_placeholder: Search Tile Developers Guide 1.12
      local_product_version: '1.12'
      url_prefix: tiledev/1-12
      local_header_links:
        - <a href="https://network.pivotal.io/">Download</a>
        - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
        - <a href="https://discuss.pivotal.io/hc/en-us/categories/200072648-Pivotal-CF-Knowledge-Base">PCF Knowledge Base</a>
      local_header_version_list:
        - url_prefix: https://docs.pivotal.io/tiledev/1-12
          display_name: v1.12

template_variables:                             # optional
