---
template_variables:
  book_title: Pivotal Documentation
  book_title_short: Pivotal Docs
  url_path: https://docs.pivotal.io/platform/2-8
  title: <span class="title-deemph">Pivotal</span> Documentation
  title_image: images/icon-p-green.jpg
  hero_text: "Detailed documentation to help you install, understand, and succeed with Pivotal's enterprise-grade software."
  product_dev_local: Pivotal Platform Dev
  product_link: <div class="header-item"><a href="https://network.pivotal.io/products/pivotal-cf">Back to Product Page</a></div>
  product_url: https://network.pivotal.io/products/pivotal-cf
  support_link: <a href="https://pivotal.io/support" target="_blank">Support</a>
  support_call_to_action: <a href="https://pivotal.io/support" target="_blank">Need Support?</a>
  support_url: https://pivotal.io/support
  path_to_partials: /pcf
  use_global_header: true
  global_header_product_href: https://network.pivotal.io/
  global_header_product_link_text: Downloads
  current_major_version: "2.8"
  v_major_version: "v2.8"
  api_version: "259"
  ga_account_id: UA-39702075-1
  gtm_account_id: GTM-MW4LZHR

# Product variables
  platform_name: Pivotal Platform
  platform_old: Pivotal Cloud Foundry
  platform_code: PCF
  product_name_lc: pcf
  app_runtime_full: Pivotal Application Service
  app_runtime: Application Service
  app_runtime_abbr: PAS
  app_runtime_abbr_lc: pas
  k8s_runtime_full: Enterprise Pivotal Container Service
  k8s_runtime: Enterprise PKS
  k8s_runtime_abbr: PKS
  windows_runtime_full: Pivotal Application Service for Windows
  windows_runtime: Application Service for Windows
  windows_runtime_abbr: PASW

# Deprecated variables -- replace with current product variables when possible
  product_name: Pivotal Platform
  product_runtime: Pivotal Application Service
  product_short: PAS

# Book content variables
  recommended_by: Pivotal